name: Pull Request CI
on:
  pull_request:
    branches:
      - 1.17.x
      - 1.15.x
      - 1.x
      - 2.x
      - 2.2.x
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: ['11', '17', '21']
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      # ELY-2204 - Temporarily preventing OidcTest from running on macOS since there
      # are intermittent issues with starting up the Docker container.
      #- if: matrix.os == 'macos-latest'
      #  name: Install docker
      #  run: |
      #    brew install docker docker-machine docker-compose
      #    brew services start docker-machine
      #    docker-machine create --driver virtualbox default
      #    docker --version
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Version Info
        run: mvn -version
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
